// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dilmmsrsrjdzjrzkljzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbG1tc3JzcmpkempyemtsanpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDMzNDEsImV4cCI6MjA3MjQ3OTM0MX0.1-qWA_u_MMRAxX3LnLO7DC7fvPhbR3pXbu_raOccBPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});